# Generated by Django 3.0.4 on 2020-03-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200321_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish_id',
            field=models.IntegerField(default=0),
        ),
    ]
